configfile: "config/config.yaml"

rule all:
	input:
		"results/hail_gather_data/for_sample_QC.tsv",
		"results/hail_gather_data/sampleqc.tsv",
		"results/hail_gather_data/plot_sampleQC.html",
		"results/normalized/df3_norm.vcf.gz",
		"results/PCA/populations_PCA.html",
		"results/array_comparison/array_comp.con",
		directory("results/prune_filter/filtered"),
		"results/kinship/king.kin0",
		"results/common_vars_for_gwas/eurs.fam",
		"results/PRS/variants_for_prs.vcf.bgz",
		expand("results/saige/{contig}GWAS_EUR_A2.saige.txt", contig=config["contigs_wo_X"]+[23]),
		"results/saige/allChrGWAS_EUR_A2.saige.txt.gz",
		"results/all_vars_for_RVAS/eurs.vcf.bgz",
		"results/regenie/RVAS_EUR_POP_A2_A2.regenie.gz",
		"results/regenie/RVAS_EUR_POP_B2_B2.regenie.gz",
		"results/regenie/GWAS_EUR_A2.regenie.gz",
		"results/regenie/GWAS_EUR_B2.regenie.gz",


# START # GENERAL QC ############################################################################################################################################

# normalize the vcf file and annotate it with the ID: CHROM:POS:REF:ALT
rule normalize_vcf_annotate_bcftools:
	input:
		bcf=config["input_vcf"],
		fasta=config["fasta"]
	output:
		vcf_gz="results/normalized/df3_norm.vcf.gz",
		vcf_gz_index="results/normalized/df3_norm.vcf.gz.tbi"
	resources: cpus=1, mem_mb=8000, time_job=10080
	params:
		partition=config["long"]
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		#wget -nc ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
		#gzip -d GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
		bcftools filter -r chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX \
		  {input.bcf} -Ou | \
		  bcftools norm --check-ref w -f {input.fasta} -Ou | \
		  bcftools annotate --set-id '%CHROM:%POS:%REF:%FIRST_ALT' -Oz > {output.vcf_gz}
		tabix -p vcf {output.vcf_gz}
		"""


# Just calculate sample QC-data using hail
rule ConvertToHail:
	input:
		"results/normalized/df3_norm.vcf.gz"
	output:
		hail_MT=directory("results/normalized/hail_MT"),
	resources: cpus=4, mem_mb=10000, time_job=10080, additional=" -x " + config["master_nodes_excluded"]
	params:
		partition=config["long"],
		tmp_dir=config["tmp_folder"],
	conda: "spark"
	shell:
		"""
		mkdir -p {params.tmp_dir}
		
		hail_python_script="workflow/scripts/vcf2hail.py $(pwd)/{input} $(pwd)/{output} {params.tmp_dir}"
		
		if [ {config[cluster]} = "yes" ]; then
		worker_nodes_excluded={config[worker_nodes_excluded]}
		num_workers=15
		source workflow/scripts/spark_submit_command.sh
		$spark_submit_command $hail_python_script
		
		else
		python $hail_python_script
		fi
		"""

rule prefilter:
	input:
		mt="results/normalized/hail_MT",
		bed="resources/regions_of_high_LD.bed"
	output:		
		out_mt=directory("results/prune_filter/filtered"),
		out_plink="results/prune_filter/plink_filtered.fam",
		out_plink_bim="results/prune_filter/plink_filtered.bim",
		out_plink_bed="results/prune_filter/plink_filtered.bed",
		sample_qc_file="results/hail_gather_data/sampleqc.tsv",
	resources: cpus=4, mem_mb=80000, time_job=720, additional=" --ntasks=1 " #-x " + config["master_nodes_excluded"] # --gres localtmp:300G
	params:
		partition=config["medium"],
		tmp_dir=config["tmp_folder"] +"prune_filter/",
		out_plink=lambda wildcards, output: output["out_plink"][:-4],
	conda: "spark"
	shell:
		"""	
		mkdir -p {params.tmp_dir}
		
		hail_python_script="workflow/scripts/prune_filter.py $(pwd)/{input.mt} $(pwd)/{params.tmp_dir} $(pwd)/{input.bed} $(pwd)/{output.out_mt} $(pwd)/{params.out_plink} $(pwd)/{output.sample_qc_file}"
		
		if [ {config[cluster]} = "yes" ]; then
		queue="medium"
		export TMPDIR=$(pwd)/{params.tmp_dir}
		hours_to_run=12
		DRIVE_MEM=78
		SPARK_LOCAL_DIRS=$(pwd)/{params.tmp_dir}
		worker_nodes_excluded={config[worker_nodes_excluded]}
		num_workers=60
		source workflow/scripts/spark_submit_command.sh
		$spark_submit_command $hail_python_script
		
		else
		python $hail_python_script
		fi
		
		rm -rf {params.tmp_dir}*
		"""


# reformat the hail sample QC file, generate histograms of all values, generate a list of samples passing the sample QC thresholds 
rule ReformatPlotSampleQC:
	input:
		sampleQC="results/hail_gather_data/sampleqc.tsv",
		xl_file=config["pheno_excel"]
	output:
		"results/hail_gather_data/plot_sampleQC.html",
		"results/hail_gather_data/for_sample_QC.tsv"
	resources: cpus=1, mem_mb=4000, time_job=720
	params:
		partition=config["medium"],
		path_output="results/hail_gather_data/"
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		echo $(pwd)

		cp workflow/scripts/plot_sampleQC.R {params.path_output}
		cp {input.xl_file} {params.path_output}
		
		cd {params.path_output}
		
		Rscript -e 'library(rmarkdown); rmarkdown::render("plot_sampleQC.R", "html_document")'
		rm *.R
		"""


rule prune:
	input:
		in_plink="results/prune_filter/plink_filtered.fam"
	output:		
		out_plink="results/prune_filter/plink_pruned_filtered.fam",
		bim="results/prune_filter/plink_pruned_filtered.bim",
		bed="results/prune_filter/plink_pruned_filtered.bed",
	resources: cpus=4, mem_mb=16000, time_job=720, additional=" --ntasks=1 " #-x " + config["master_nodes_excluded"] # --gres localtmp:300G
	params:
		partition=config["medium"],
		in_plink=lambda wildcards, input: input["in_plink"][:-4],
		out_plink=lambda wildcards, output: output["out_plink"][:-4],
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		plink \
		--bfile  {params.in_plink} \
		--indep-pairwise 50kb 5 0.2 \
		--out {params.out_plink}
		
		plink \
		--bfile  {params.in_plink} \
		--extract {params.out_plink}.prune.in \
		--make-bed \
		--out {params.out_plink}
		"""

#### Population PCA W 1000G project

rule download_1000G_sample_info:
	output:
		#"GCA_000001405.15_GRCh38_no_alt_analysis_set.fna",
		"results/PCA/20130606_g1k.ped" # contig = chr1, ...
	resources: cpus=1, mem_mb=3000, time_job=720
	params:
		out_folder="results/PCA/",
		partition=config["medium"]
	shell:
		"""
		mkdir -p {params.out_folder}
		cd {params.out_folder}
		wget -nc ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20130606_sample_info/20130606_g1k.ped
		
		#reference genome  (GRCh38)
		#wget -nc ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
		#gzip -d GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
		"""

rule download_1000G_genotypes:
	output:
		config["location_1000G"]+"/ALL.chr{contig}.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz",
		config["location_1000G"]+"/ALL.chr{contig}.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz.tbi"#
	resources: cpus=1, mem_mb=3000, time_job=720
	params:
		partition=config["medium"],
		folder_cont=config["location_1000G"]
	shell:
		"""
		mkdir -p {params.folder_cont}
		cd {params.folder_cont}
		prefix="ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20181203_biallelic_SNV/ALL.chr"
		suffix=".shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz"
		wget -nc "$prefix""{wildcards.contig}""$suffix" "$prefix""{wildcards.contig}""$suffix".tbi
		"""


rule prepare_1000G_for_ancestry_PCA:
	input:
		vcf=config["location_1000G"]+"/ALL.chr{contig}.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz",
		fasta=config["fasta"], #/ceph01/projects/bioinformatics_resources/Genomes/Human/GATK/hg38/Homo_sapiens_assembly38.fasta
		hailbim="results/prune_filter/plink_filtered.bim",
	output:
		bcf="results/1000G/1000G_chr{contig}.bcf",
		bed2="results/1000G/1000G_chr{contig}_pruned.bed"
	resources: cpus=1, mem_mb=18000, time_job=720
	conda:
		"envs/bcftools_plink_R.yaml"
	params:
		partition=config["medium"],
		bed1="results/1000G/1000G_chr{contig}",
		bed2="results/1000G/1000G_chr{contig}_pruned"
	shell:
		"""
		if bcftools view -q 0.05:minor {input.vcf} | \
		bcftools norm -m-any --check-ref w -f "{input.fasta}" | \
		bcftools annotate -x ID -I +'%CHROM:%POS:%REF:%ALT' | \
		bcftools norm -Ob --rm-dup both \
		> {output.bcf} ; then
		echo "no error"
		fi
		
		plink --noweb \
		--bcf {output.bcf} \
		--keep-allele-order \
		--vcf-idspace-to _ \
		--allow-extra-chr 0 \
		--split-x b38 no-fail \
		--make-bed \
		--out {params.bed1}
		
		plink --noweb \
		--bfile {params.bed1} \
		--extract {input.hailbim} \
		--maf 0.10 --indep 50 5 1.5 \
		--make-bed \
		--out {params.bed2}
		"""
		
rule merge_data_w_1000G_run_PCA:
	input:
		_1000G_data=expand("results/1000G/1000G_chr{contig}_pruned.bed", contig=config["contigs_wo_X"]), #### !!!!! 
		hailbim="results/prune_filter/plink_filtered.bim",
		ped_file_1000G="results/PCA/20130606_g1k.ped"
	output:
		merge_list="results/1000G/merge_list.txt",
		bim_pca="results/PCA/MergeFullForPCA.bim",
		pca="results/PCA/MergeFullForPCA.eigenvec",
	resources: cpus=1, mem_mb=18000, time_job=720
	params:
		partition=config["medium"],
		hailplink=lambda wildcards, input: input["hailbim"][:-4],
		pca_prefix=lambda wildcards, output: output["bim_pca"][:-4],
	conda:
		"spark"
	shell:
		"""
		echo {input._1000G_data} | tr " " "\\n" | sed 's/.bed//g' > {output.merge_list}
		plink --merge-list {output.merge_list} --out results/1000G/Merged
		awk '{{ print $2 }}' results/1000G/Merged.bim > results/1000G/MergeVariants.txt
		
		plink --bfile {params.hailplink} \
		 --extract results/1000G/MergeVariants.txt \
		 --make-bed \
		 --out results/1000G/hail_for_ancestry
		 
		printf "results/1000G/Merged\\nresults/1000G/hail_for_ancestry" > results/1000G/ForMergeFull.list
		
		mkdir -p results/PCA
		plink --merge-list results/1000G/ForMergeFull.list --out results/PCA/MergeFullForPCA
		 
		awk '{{ print $1,$2 }}' results/1000G/Merged.fam | awk '$(NF+1) = "1000G"' > results/PCA/clusters.txt
		awk '{{ print $1,$2 }}' results/1000G/hail_for_ancestry.fam | awk '$(NF+1) = "Cohort"' >> results/PCA/clusters.txt
		
		plink --bfile results/PCA/MergeFullForPCA \
		 --pca-cluster-names 1000G \
		 --pca \
		 --out {params.pca_prefix} \
		 --within results/PCA/clusters.txt
		"""


rule analyse_PCA_results:
	input:
		ped_file_1000G="results/PCA/MergeFullForPCA.eigenvec"
	output:
		populations="results/PCA/populations.txt",
		html="results/PCA/populations_PCA.html"
	resources: cpus=1, mem_mb=18000, time_job=720
	params:
		partition=config["medium"],
	conda:
		"envs/bcftools_plink_R.yaml"
	shell:
		"""
		cp -f workflow/scripts/populations_PCA.R results/PCA/populations_PCA.R
		cd results/PCA/
		Rscript -e 'library(rmarkdown); rmarkdown::render("populations_PCA.R", "html_document")'
		
		"""


rule kinship_analysis:
	input:
		fam="results/prune_filter/plink_pruned_filtered.fam",
	output:
		kinship_file1="results/kinship/king.kin0",
	resources: cpus=4, mem_mb=16000, time_job=720, additional=" --ntasks=1 " #-x " + config["master_nodes_excluded"] # --gres localtmp:300G
	params:
		partition=config["medium"],
		plink_in=lambda wildcards, input: input["fam"][:-4],
		prefix=lambda wildcards, output: output["kinship_file1"][:-5],
	conda: "envs/king.yaml"
	shell:
		"""
		king \
		-b {params.plink_in}.bed \
		--kinship \
		--prefix {params.prefix}
		"""

rule ApplyRelatednessFilter:
	input:
		GWAS_MT="results/prune_filter/filtered",
		pheno_file="results/hail_gather_data/for_sample_QC.tsv"
	output:		
		kinship_vals="results/kinship/hail_kinship_coefficients.tsv",
		to_remove="results/kinship/relatives_to_remove.tsv",
	resources: cpus=8, mem_mb=80000, time_job=2880, additional=" --ntasks=1 -x " + config["master_nodes_excluded"] #--gres localtmp:300G 
	params:
		partition=config["long"],
		tmp_dir=config["tmp_folder"] +"kinship/",
	conda: "spark"
	shell:
		"""	
		mkdir -p {params.tmp_dir}
		
		hail_python_script="workflow/scripts/relatedness_filter.py $(pwd)/{input.GWAS_MT} $(pwd)/{params.tmp_dir} $(pwd)/{input.pheno_file} $(pwd)/{output.kinship_vals} $(pwd)/{output.to_remove}"
		
		if [ {config[cluster]} = "yes" ]; then
		queue="long"
		hours_to_run=168
		DRIVE_MEM=78
		worker_nodes_excluded={config[worker_nodes_excluded]}
		num_workers=20
		source workflow/scripts/spark_submit_command.sh
		$spark_submit_command $hail_python_script
		
		else
		python $hail_python_script
		fi
		
		rm -rf {params.tmp_dir}*
		"""


rule extract_dbSNP_file:
	input:
		"resources/dbSNP_hg38_pos_chr18_dedup.txt.gz"
	output:
		pos="results/array_comparison/dbnsfp_pos.txt",
		ids="results/array_comparison/dbnsfp_ids.txt",
	resources: cpus=1, mem_mb=4000, time_job=720
	params:
		partition=config["medium"],
	shell:
		"""
		zcat {input} > {output.pos}
		zcat {input} | cut -f1 -d" " > {output.ids}
		"""

rule make_plink_seq_data:
	input:
		vcf="results/normalized/df3_norm.vcf.gz",
		array_fam="results/array_comparison/array_local.fam",
		dbnsfp_pos="results/array_comparison/dbnsfp_pos.txt"
	output:
		allplink="results/array_comparison/seq.fam"
	resources: cpus=2, mem_mb=16000, time_job=2880
	params:
		partition=config["long"],
		plink_pref=lambda wildcards, output: output["allplink"][:-4],
		array_plink=lambda wildcards, input: input["array_fam"][:-4],
	conda: "spark"
	shell:
		"""
		plink \
		 --vcf {input.vcf} \
		 --chr 18 \
		 --vcf-half-call h \
		 --double-id \
		 --make-bed \
		 --out {params.plink_pref}_tmp
		
		plink \
		--bfile {params.plink_pref}_tmp \
		--update-name "{input.dbnsfp_pos}" 1 4 \
		--make-just-bim \
		--out {params.plink_pref}_tmp2
		
		cat {params.plink_pref}_tmp2.bim | sed "s/chr//g" > {params.plink_pref}_tmp.bim
		
		plink \
		--fam {params.plink_pref}_tmp.fam \
		--bed {params.plink_pref}_tmp.bed \
		--bim {params.plink_pref}_tmp.bim \
		--extract {params.array_plink}.bim \
		--make-bed \
		--out {params.plink_pref}
		
		rm -f {params.plink_pref}_tmp*
		""" 
		
rule rename_plink_array:
	input:
		arrayfam=config["array_files"],
		dbnsfp_ids="results/array_comparison/dbnsfp_ids.txt",
		dbnsfp_pos="results/array_comparison/dbnsfp_pos.txt"
	output:	
		array_fam="results/array_comparison/array_local.fam",
	resources: cpus=2, mem_mb=16000, time_job=2880
	params:
		partition=config["long"],
		ar_pl_in=lambda wildcards, input: input["arrayfam"][:-4],
		ar_pl_out=lambda wildcards, output: output["array_fam"][:-4],
	conda: "spark"
	shell:
		"""
		plink \
		 --bfile "{params.ar_pl_in}" \
		 --extract "{input.dbnsfp_ids}" \
		 --make-bed \
		 --out {params.ar_pl_out}_tmp1
		
		plink \
		 --bfile {params.ar_pl_out}_tmp1 \
		 --update-map "{input.dbnsfp_pos}" 3 1 \
		 --make-bed \
		 --out {params.ar_pl_out}
		
		awk '{{print $2"ARRAY",$2"ARRAY",$3,$4,$5,$6}}' {params.ar_pl_out}.fam > {params.ar_pl_out}_tmp.fam
		mv {params.ar_pl_out}_tmp.fam {params.ar_pl_out}.fam
		rm -f {params.ar_pl_out}_tmp*
		"""

rule compare_w_array_king:
	input:
		array_fam="results/array_comparison/array_local.fam",
		sequencing_fam="results/array_comparison/seq.fam",
	output:	
		kinship_vals="results/array_comparison/array_comp.con",
	resources: cpus=4, mem_mb=32000, time_job=720
	params:
		partition=config["medium"],
		hl_pl=lambda wildcards, input: input["sequencing_fam"][:-4],
		ar_pl=lambda wildcards, input: input["array_fam"][:-4],
		king_prefix=lambda wildcards, output: output["kinship_vals"][:-4],
		
	conda: "envs/king.yaml"
	shell:
		"""
		#module load king
	
		king \
		-b {params.hl_pl}.bed,{params.ar_pl}.bed \
		--duplicate \
		--related \
		--degree 1 \
		--prefix {params.king_prefix}
		"""




# END # GENERAL QC #############################################################################################################################################

# START # PHENO COVAR FILES #############################################################################################################################################


rule generate_pheno_files_for_GWAS:
	input:
		fam="results/common_vars_for_gwas/eurs.fam",
		individual_list="resources/Eurs_phenofile.tsv"
	output:
		fam="results/regenie_pheno/fam_{population}_{pheno}.fam",
		pheno="results/regenie_pheno/pheno_{population}_{pheno}.pheno"
	resources: cpus=1, mem_mb=3000, time_job=720
	conda:
		"envs/bcftools_plink_R.yaml"
	params:
		partition=config["medium"],
		path="results/regenie_pheno/"
	shell:
		"""
		mkdir -p {params.path} 
		Rscript workflow/scripts/generate_regenie_pheno.R {input.individual_list} {input.fam} {wildcards.pheno} {output.fam} {output.pheno}
		"""


rule generate_PCA_covar_for_GWAS:
	input:
		fam="results/regenie_pheno/fam_{population}_{pheno}.fam",
		bim="results/common_vars_for_gwas/eurs.bim",
		bed="results/common_vars_for_gwas/eurs.bed",
	output:
		"results/PCAcovar/{pheno}_{population}_PCA.eigenvec"
	resources: cpus=1, mem_mb=18000, time_job=720
	params:
		partition=config["medium"],
		folderPCA="results/PCAcovar",
		plink_in=lambda wildcards, input: input["fam"][:-4],
		pathinterim="results/PCAcovar/{pheno}_{population}__interimfiles",
		pathPCA="results/PCAcovar/{pheno}_{population}_PCA"
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		mkdir -p {params.folderPCA}
		
		#common
		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--biallelic-only strict \
		--chr 1-22 \
		--geno 0.05 \
		--snps-only 'just-acgt' \
		--hwe 1E-6 midp \
		--indep-pairwise 50 5 0.05 \
		--keep-allele-order \
		--mac 5 \
		--maf 0.01 \
		--out "{params.pathinterim}"

		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--extract "{params.pathinterim}.prune.in" \
		--pca 10 \
		--out "{params.pathPCA}"
		rm {params.pathinterim}*
		"""


rule generate_covar_files_GWAS:
	input:
		PCA_cov="results/PCAcovar/{pheno}_{population}_PCA.eigenvec",
		individual_list="resources/Eurs_phenofile.tsv"
	output:
		"results/regenie_pheno/cov_{population}_{pheno}.cov"
	resources: cpus=1, mem_mb=3000, time_job=720
	params:
		partition=config["medium"],
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		Rscript workflow/scripts/generate_covar_file.R {input.individual_list} {input.PCA_cov} {output}
		"""


rule make_pheno_cov_saige:
	input:
		pathCov="results/regenie_pheno/cov_{population}_{pheno}.cov",
		pathPheno="results/regenie_pheno/pheno_{population}_{pheno}.pheno", 
	output:
		"results/regenie_pheno/cov_{population}_{pheno}.phenocov",
		"results/regenie_pheno/cov_{population}_{pheno}.males",
	resources: cpus=1, mem_mb=18000, time_job=720
	params:
		partition=config["medium"],
	conda: "envs/bcftools_plink_R.yaml"
	script: "scripts/make_phenoCov.R"


rule CompilePhenoInfo:
	input:
		xl_file=config["pheno_excel"],
		qc_file="results/hail_gather_data/for_sample_QC.tsv"
	output:
		AgePlot="results/plotPhenoInfo/AgePlot.pdf",

	resources: cpus=1, mem_mb=6000, time_job=720, additional=" --ntasks=1 "
	params:
		partition=config["medium"],
		out_dir="results/plotPhenoInfo/",
	conda: "spark"
	shell:
		"Rscript workflow/scripts/compile_phenotype_plots.R {input} {params.out_dir}"


# END # PHENO COVAR FILES #############################################################################################################################################

# START # GWAS #############################################################################################################################################

rule QC_pre_GWAS:
	input:
		MT=directory("results/normalized/hail_MT"),
		individual_list="resources/Eurs_phenofile.tsv"
	output:
		fam="results/common_vars_for_gwas/eurs.fam",
		bim="results/common_vars_for_gwas/eurs.bim",
		bed="results/common_vars_for_gwas/eurs.bed",
		mt=directory("results/common_vars_for_gwas/eurs_mt")
	resources: cpus=4, mem_mb=10000, time_job=720, additional=" -x " + config["master_nodes_excluded"]
	params:
		partition=config["long"],
		tmp_dir=config["tmp_folder"],
		plink_prefix=lambda wildcards, output: output["fam"][:-4],
	conda: "spark"
	shell:
		"""
		mkdir -p {params.tmp_dir}
		
		hail_python_script="workflow/scripts/MakeCommonVarPLINK.py $(pwd)/{params.tmp_dir} $(pwd)/{input.MT} $(pwd)/{input.individual_list} $(pwd)/{params.plink_prefix}"
		
		if [ {config[cluster]} = "yes" ]; then
		worker_nodes_excluded={config[worker_nodes_excluded]}
		num_workers=10
		source workflow/scripts/spark_submit_command.sh
		$spark_submit_command $hail_python_script
		
		else
		python $hail_python_script
		fi
		"""


rule additional_GWAS_Specifc_QC:
	input:
		fam="results/regenie_pheno/fam_{population}_{pheno}.fam",
		bim="results/common_vars_for_gwas/eurs.bim",
		bed="results/common_vars_for_gwas/eurs.bed",
	output:
		bed="results/additional_QC/{population}_{pheno}/not_rel_QCed.bed",
		bim="results/additional_QC/{population}_{pheno}/not_rel_QCed.bim",
		fam="results/additional_QC/{population}_{pheno}/not_rel_QCed.fam"
	resources: cpus=6, mem_mb=90000, time_job=720, additional=" "
	params:
		partition=config["medium"],
		pathQC="results/additional_QC/{population}_{pheno}"
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		mkdir -p {params.pathQC}
		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--filter-cases \
		--missing \
		--out {params.pathQC}/Geno05_CR_sex_snp_qc_snpqcCAS
		
		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--filter-controls \
		--missing \
		--out {params.pathQC}/Geno05_CR_sex_snp_qc_snpqcCON
		
		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--hardy \
		--out {params.pathQC}/Geno05_CR_sex_snp_qc_snpqcALL
				
		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--hardy \
		--chr 23 \
		--filter-females \
		--out {params.pathQC}/Geno05_CR_sex_snp_qc_snpqcALL_female

		### R session
		wd=$(pwd)
		cp workflow/scripts/additional_QC_cohort.R {params.pathQC}/
		cd {params.pathQC}
		Rscript -e 'library(rmarkdown); rmarkdown::render("additional_QC_cohort.R", "html_document")'
		cd $wd
		
		# 1e. final QC (4675116)
		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--exclude {params.pathQC}/missingness_hardy_weinberg_filter.txt \
		--make-bed \
		--out {params.pathQC}/not_rel_QCed
		"""

rule get_plink_step1:
	input:
		keep_fam="results/regenie_pheno/fam_{population}_{pheno}.fam",
		fam="results/prune_filter/plink_pruned_filtered.fam",
		bim="results/prune_filter/plink_pruned_filtered.bim",
		bed="results/prune_filter/plink_pruned_filtered.bed",
	output:
		fam="results/regenie/pheno_{population}_{pheno}_pruned_plink.fam",
		bim="results/regenie/pheno_{population}_{pheno}_pruned_plink.bim",
		bed="results/regenie/pheno_{population}_{pheno}_pruned_plink.bed",
		var_ids="results/regenie/pheno_{population}_{pheno}_pruned_plink.txt",
	resources: cpus=1, mem_mb=10000, time_job=720
	params:
		partition=config["medium"],
		pruned_plink=lambda wildcards, output: output["bim"][:-4],
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		# LD pruned variants for regenie step 1
		plink \
		--bed {input.bed} \
		--bim {input.bim} \
		--fam {input.fam} \
		--keep {input.keep_fam} \
		--maf 0.01 \
		--chr 1-22 \
		--geno 0.01 \
		--snps-only just-acgt \
		--hwe 1e-10 \
		--exclude range resources/longrange_LD_regions_hg38_GRCh38.txt \
		--make-bed \
		--out {params.pruned_plink}
		
		cut -f2 {output.bim} > {output.var_ids}
		
		"""

rule Regenie_step1:
	input:
		pathCov="results/regenie_pheno/cov_{population}_{pheno}.cov",
		pathPheno="results/regenie_pheno/pheno_{population}_{pheno}.pheno", 
		filtered="results/regenie/pheno_{population}_{pheno}_pruned_plink.txt",
		fam="results/prune_filter/plink_pruned_filtered.fam",
		bim="results/prune_filter/plink_pruned_filtered.bim",
		bed="results/prune_filter/plink_pruned_filtered.bed",
	output:
		step1="results/regenie/pheno_{population}_{pheno}_step1_pred.list"
	resources: cpus=1, mem_mb=18000, time_job=720
	conda: "envs/regenie.yaml"
	params:
		partition=config["medium"],
		plink_file=lambda wildcards, input: input["fam"][:-4],
		step1=lambda wildcards, output: output["step1"][:-10],
	shell:
		"""
		#export LD_LIBRARY_PATH={config[LD_LIBRARY_PATH]}
		
		regenie \
		  --step 1 \
		  --bed {params.plink_file} \
		  --covarFile {input.pathCov} \
		  --phenoFile {input.pathPheno} \
		  --bt \
		  --extract {input.filtered} \
		  --loocv \
		  --bsize 1000 \
		  --out {params.step1}
		#--extract input.pruned \
		 """

rule Regenie_step2_GWAS:
	input:
		pathCov="results/regenie_pheno/cov_{population}_{pheno}.cov",
		pathPheno="results/regenie_pheno/pheno_{population}_{pheno}.pheno",
		step1="results/regenie/pheno_{population}_{pheno}_step1_pred.list",
		bed="results/additional_QC/{population}_{pheno}/not_rel_QCed.bed",
		bim="results/additional_QC/{population}_{pheno}/not_rel_QCed.bim",
		fam="results/additional_QC/{population}_{pheno}/not_rel_QCed.fam"
	output:
		path_reg="results/regenie/GWAS_{population}_{pheno}.regenie.gz"
	resources: cpus=1, mem_mb=18000, time_job=720
	conda: "envs/regenie.yaml"
	params:
		partition=config["medium"],
		plink_file=lambda wildcards, input: input["fam"][:-4],
		regenie_step2=lambda wildcards, output: output["path_reg"][:-14]
	shell:
		"""
		#export LD_LIBRARY_PATH={config[LD_LIBRARY_PATH]}

		regenie \
		  --step 2 \
		  --minMAC 10 \
		  --covarFile {input.pathCov} \
		  --phenoFile {input.pathPheno} \
		  --bed {params.plink_file} \
		  --bt \
		  --spa \
		  --htp DeCOI \
		  --ignore-pred \
		  --write-samples \
		  --bsize 1000 \
		  --out {params.regenie_step2} \
		  --gz

		  #--pred {input.step1} \
		  #--firth --approx \
		  #--firth-se \
		  #--maxstep-null 5 \
		  #--maxiter-null 10000 \
		  """

rule plink2_GWAS:
	input:
		covar="results/regenie_pheno/cov_{population}_{pheno}.cov",
		bed="results/additional_QC/{population}_{pheno}/not_rel_QCed.bed",
		bim="results/additional_QC/{population}_{pheno}/not_rel_QCed.bim",
		fam="results/regenie_pheno/fam_{population}_{pheno}.fam",
	output:
		plink_gwas="results/regenie/GWAS_{population}_{pheno}.PHENO1.glm.logistic"
	resources: cpus=1, mem_mb=18000, time_job=720
	conda: "envs/bcftools_plink_R.yaml"
	params:
		partition=config["medium"],
		plink_out=lambda wildcards, output: output["plink_gwas"][:-20]
	shell:
		"""
		plink2 \
		--bim {input.bim} \
		--bed {input.bed} \
		--fam {input.fam} \
		--glm no-x-sex hide-covar log10 \
		--covar {input.covar} \
		--covar-variance-standardize \
		--out {params.plink_out} \
		--mac 20
		  """

rule SAGE_step1:
	input:
		phenocov="results/regenie_pheno/cov_{population}_{pheno}.phenocov",
		fam="results/regenie/pheno_{population}_{pheno}_pruned_plink.fam",
		bim="results/regenie/pheno_{population}_{pheno}_pruned_plink.bim",
		bed="results/regenie/pheno_{population}_{pheno}_pruned_plink.bed",
	output:
		step1="results/saige/pheno_{population}_{pheno}.rda"
	resources: cpus=1, mem_mb=18000, time_job=720
	conda: "envs/saige.yaml"
	params:
		partition=config["medium"],
		plink_file=lambda wildcards, input: input["fam"][:-4],
		step1=lambda wildcards, output: output["step1"][:-4],
	shell:
		"""
		step1_fitNULLGLMM.R \
		--plinkFile={params.plink_file} \
		--phenoFile={input.phenocov} \
		--phenoCol={wildcards.pheno} \
		--covarColList=PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,Age,Age2,age_sex,sex_for_fam \
		--sampleIDColinphenoFile=IID \
		--traitType=binary \
		--outputPrefix={params.step1} \
		--LOCO=TRUE \
		--IsOverwriteVarianceRatioFile=TRUE \
		--nThreads=4
		"""

rule make_saige_vcf_from_plink:
	input:
		bed="results/additional_QC/{population}_{pheno}/not_rel_QCed.bed",
		bim="results/additional_QC/{population}_{pheno}/not_rel_QCed.bim",
		fam="results/additional_QC/{population}_{pheno}/not_rel_QCed.fam"
	output:
		vcf="results/additional_QC/{population}_{pheno}/not_rel_QCed.vcf.gz",
		vcf_justX="results/additional_QC/{population}_{pheno}/not_rel_QCed_justX.vcf.gz",
	resources: cpus=1, mem_mb=18000, time_job=720
	params:
		partition=config["medium"],
		vcfprefix=lambda wildcards, output: output["vcf"][:-7],
		vcfprefix_justX=lambda wildcards, output: output["vcf_justX"][:-7],
		plink_in=lambda wildcards, input: input["fam"][:-4],
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		plink \
		--bfile {params.plink_in} \
		--recode vcf-iid \
		--out {params.vcfprefix}
		
		cat  {params.vcfprefix}.vcf | bgzip > {output.vcf}
		tabix --csi -pvcf {output.vcf}

		plink \
		--bfile {params.plink_in} \
		--recode vcf-iid \
 		--chr X \
		--out {params.vcfprefix_justX}

 		cat  {params.vcfprefix_justX}.vcf | bgzip > {output.vcf_justX}
 		tabix --csi -pvcf {output.vcf_justX}
		
		"""

rule SAIGE_step2_GWAS:
	input:
		pathCov="results/regenie_pheno/cov_{population}_{pheno}.cov",
		pathPheno="results/regenie_pheno/pheno_{population}_{pheno}.pheno",
		step1="results/saige/pheno_{population}_{pheno}.rda",
		vcf="results/additional_QC/{population}_{pheno}/not_rel_QCed.vcf.gz",
		vcf_justX="results/additional_QC/{population}_{pheno}/not_rel_QCed_justX.vcf.gz",
		males="results/regenie_pheno/cov_{population}_{pheno}.males",
	output:
		path_saige="results/saige/{chrom}GWAS_{population}_{pheno}.saige.txt"
	resources: cpus=1, mem_mb=18000, time_job=720
	conda: "envs/saige.yaml"
	params:
		partition=config["medium"],
		saige_step1=lambda wildcards, input: input["step1"][:-4],
		in_vcf=lambda wildcards, input: input["vcf_justX"] if (str(wildcards["chrom"])=="23") else input["vcf"],
		loco=lambda wildcards, input: "--LOCO=TRUE --chrom=" + str(wildcards["chrom"]) if (str(wildcards["chrom"])!="23") else "--LOCO=FALSE --chrom=23 --X_PARregion=10001-2781479,155701383-156030895 --sampleFile_male="+input["males"]+" --is_rewrite_XnonPAR_forMales=TRUE",
	shell:
		"""
		
		step2_SPAtests.R \
		--vcfField=GT \
		--GMMATmodelFile={params.saige_step1}.rda \
		--varianceRatioFile={params.saige_step1}.varianceRatio.txt \
		--SAIGEOutputFile={output} \
		--numLinesOutput=1000 \
		--IsOutputNinCaseCtrl=TRUE \
		--IsOutputHetHomCountsinCaseCtrl=TRUE \
		--minMAC=3 \
		--IsOutputAFinCaseCtrl=TRUE \
		--vcfFile={params.in_vcf} {params.loco}	

		"""

rule merge_saige_GWAS:
	input:
		expand("results/saige/{chrom}GWAS_{population}_{pheno}.saige.txt", chrom=config["contigs_wo_X"]+[23], allow_missing=True)
	output:
		path_saige="results/saige/allChrGWAS_{population}_{pheno}.saige.txt.gz"
	resources: cpus=1, mem_mb=18000, time_job=720
	params:
		header="results/saige/GWAS_{population}_{pheno}_header.txt",
		partition=config["medium"],
	shell:
		"""
		if cat {input} | grep "CHR" | head -n1 > {params.header}
		then
		echo "don't worry"
		fi

		cat {input} | grep -v "CHR" | \
		cat {params.header} - |
		gzip > {output}
		"""


rule generate_qq_plots:
	input:
		path_reg="results/regenie/{infile}"
	output:
		"results/regenie/{infile}_LOG10P_manhattan.png" 
	resources: cpus=1, mem_mb=3000, time_job=720
	params:
		partition=config["medium"],
	conda: "envs/bcftools_plink_R.yaml"
	shell:
		"""
		Rscript workflow/scripts/qqplot.R -f {input} -o {input} -c CHROM -p LOG10P -b GENPOS
		"""


# END # GWAS #############################################################################################################################################

# START # RVAS #############################################################################################################################################

rule QC_pre_RVAS:
	input:
		MT=directory("results/normalized/hail_MT"),
		individual_list="resources/Eurs_phenofile.tsv",
		input_vcf="results/normalized/df3_norm.vcf.gz"
	output:
		fam="results/all_vars_for_RVAS/eurs.fam",
		bim="results/all_vars_for_RVAS/eurs.bim",
		bed="results/all_vars_for_RVAS/eurs.bed",
		vcf="results/all_vars_for_RVAS/eurs.vcf.bgz",
		call_rate="results/all_vars_for_RVAS/eurs_row_info.tsv.gz",
	resources: cpus=4, mem_mb=160000, time_job=1400, additional=" -x " + config["master_nodes_excluded"]
	params:
		partition=config["medium"],
		tmp_dir=config["tmp_folder"],
		out_trunk=lambda wildcards, output: output["fam"][:-4],
	conda: "spark"
	shell:
		"""
		mkdir -p {params.tmp_dir}
		
		hail_python_script="workflow/scripts/MakeRareVar.py $(pwd)/{params.tmp_dir} $(pwd)/{input.MT} $(pwd)/{input.input_vcf} $(pwd)/{input.individual_list} $(pwd)/{params.out_trunk}"
		
		if [ {config[cluster]} = "yes" ]; then
		export TMPDIR=$(pwd)/{params.tmp_dir}
		worker_nodes_excluded={config[worker_nodes_excluded]}
		hours_to_run=12
		DRIVE_MEM=148
		num_workers=60
		source workflow/scripts/spark_submit_command.sh
		$spark_submit_command $hail_python_script
		
		else
		python $hail_python_script
		fi
		"""

rule Regenie_step2_RVAS:
	input:
		pathCov="results/regenie_pheno/cov_{population}_{pheno}.cov",
		pathPheno="results/regenie_pheno/pheno_{population}_{pheno}.pheno",
		step1="results/regenie/pheno_{population}_{pheno}_step1_pred.list",
		plink_file="results/all_vars_for_RVAS/eurs.bed",
		regenie_anno_file=config["annotations_dir"]+"all_contigs_anno.file.txt",
		regenie_aaf_file=config["annotations_dir"]+"all_contigs_aaf.file.txt",
		regenie_set_list=config["annotations_dir"]+"all_contigs_set.list.txt",
		regenie_mask_def="resources/mask_definition.mask"
	output:
		path_reg="results/regenie/RVAS_{population}_POP_{pheno}_{pheno}.regenie.gz",
		mask_bed="results/regenie/RVAS_{population}_POP_{pheno}_masks.bed",
		mask_fam="results/regenie/RVAS_{population}_POP_{pheno}_masks.fam",
		mask_bim="results/regenie/RVAS_{population}_POP_{pheno}_masks.bim",
	resources: cpus=1, mem_mb=18000, time_job=720
	conda: "envs/regenie.yaml"
	params:
		partition=config["medium"],
		plink_file=lambda wildcards, input: input["plink_file"][:-4],
		regenie_step2=lambda wildcards, output: output["path_reg"][:-14]
	shell:
		"""
		export LD_LIBRARY_PATH={config[LD_LIBRARY_PATH]}

		regenie \
		  --step 2 \
		  --minMAC 1 \
		  --covarFile {input.pathCov} \
		  --phenoFile {input.pathPheno} \
		  --aaf-file {input.regenie_aaf_file} \
		  --anno-file {input.regenie_anno_file} \
		  --mask-def {input.regenie_mask_def} \
		  --set-list {input.regenie_set_list} \
		  --bed {params.plink_file} \
		  --bt \
		  --firth-se \
		  --write-samples \
		  --bsize 1000 \
		  --htp DeCOI \
		  --ignore-pred \
		  --out {params.regenie_step2} \
		  --write-mask \
		  --af-cc \
		  --gz
		  #--pred {input.step1} \
		  #--firth --approx \
		  #--firth-se \
		  #--maxstep-null 5 \
		  #--maxiter-null 10000 \
		  
		"""

# END # RVAS #############################################################################################################################################

# START # PRS #############################################################################################################################################


rule Extract_PRS_variants:
	input:
		mt_table="results/common_vars_for_gwas/eurs_mt",
		prs_file="resources/hg38.PRS.tsv"
	output:		
		vcf_for_PRS="results/PRS/variants_for_prs.vcf.bgz"
	resources: cpus=12, mem_mb=48000, time_job=720, additional=" --ntasks=1 -x " + config["master_nodes_excluded"] # --gres localtmp:200G 
	params:
		partition=config["medium"],
		out_dir="results/PRS/",
		tmp_dir=config["tmp_folder"] +"PRS/",
	conda: "spark"
	shell:
		"""

		mkdir -p {params.out_dir}
		mkdir -p {params.tmp_dir}
		
		hail_python_script="workflow/scripts/hail_get_PRS_variants.py $(pwd)/{input.mt_table} $(pwd)/{params.tmp_dir} $(pwd)/{output} $(pwd)/{input.prs_file} $(pwd)"
		
		if [ {config[cluster]} = "yes" ]; then
		worker_nodes_excluded={config[worker_nodes_excluded]}
		num_workers=5
		source workflow/scripts/spark_submit_command.sh
		$spark_submit_command $hail_python_script
		
		else
		python $hail_python_script
		fi
		"""

# END # PRS #############################################################################################################################################

# START # ROH #############################################################################################################################################


rule Extract_Rohs_plink:
	input:
		fam="results/CommonVars/CommonVars.fam",
	output:
		ROH_file=multiext("results/ROH/bedForROHAnalysis_ROH", ".hom", ".hom.indiv", ".hom.summary", ".log")
	resources: cpus=12, mem_mb=48000, time_job=720, additional=" --gres localtmp:200G --ntasks=1 -x " + config["master_nodes_excluded"]
	params:
		partition=config["medium"],
		plink_in=lambda wildcards, input: input["fam"][:-4],
		ROH_out="results/ROH/bedForROHAnalysis_ROH",
	conda: "spark"
	shell:
		"""
		plink --bfile {params.plink_in} --out {params.ROH_out} --homozyg
		"""

rule Extract_Rohs_bcftools:
	input:
		vcf_for_GWAS="results/CommonVars/CommonVars.vcf.bgz",
	output:		
		ROH_file="results/ROH/test_roh.tsv.gz",
	resources: cpus=6, mem_mb=24000, time_job=720, additional=" "
	params:
		partition=config["medium"],
		out_dir="results/ROH/",
	conda: "spark"
	shell:
		"""
		mkdir -p {params.out_dir}


		# the code here could e.g. look like this:
		bcftools roh {input.vcf_for_GWAS} --AF-tag AF -G30 --threads 6 | \
		 gzip > {output.ROH_file}
		"""

# END # ROH #############################################################################################################################################




