---
 input_vcf: "/ceph01/homedirs/aschmidt/WGS_GWAS_pipeline/smaller_df3.vcf.gz"
 fasta: "/ceph01/projects/bioinformatics_resources/Genomes/Human/GATK/hg38/Homo_sapiens_assembly38.fasta"
 phenotypes:
  - A2
  - B2
  - C2
 location_1000G: "/ceph01/homedirs/aschmidt/scratch/WGS_GWAS_pipeline/"
 populations:
  - EUR
 contigs_wo_X:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
 tmp_folder: "tmp/"
 cluster: "yes"
 master_nodes_excluded: "b101eth0,b102eth0,b103eth0,b104eth0,b105eth0,b106eth0,b107eth0,b201eth0"
 worker_nodes_excluded: "b101eth0,b102eth0,b103eth0,b104eth0,b105eth0,b106eth0,b107eth0,b201eth0"
 PATH: "$(echo \"$PATH\" | sed -e \"s>\/gpfs01\/share\/conda\/condabin:\/gpfs01\/share\/conda\/bin:>>\")"
 PYTHONPATH: "/home/aschmidt/scratch/conda/lib/python3.9/site-packages"
 spark_master_path: "/ceph01/scratch/aschmidt/spark/spark-3.1.1-bin-hadoop3.2/sbin/start-master.sh"
 spark_worker_path: "/ceph01/scratch/aschmidt/spark/spark-3.1.1-bin-hadoop3.2/sbin/start-worker.sh"
 LD_LIBRARY_PATH: "/home/aschmidt/scratch/conda/lib"

