---
 input_bcf: "/home/aschmidt/COVID_WGS/resources/.no_upload/covid.genome.bcf"
 fasta: "/home/aschmidt/genomic_resources_hg38/fasta/Homo_sapiens_assembly38.fasta"
 location_1000G: "/home/aschmidt/genomic_resources_hg38/1KG/"
 database_dir: "/home/aschmidt/genomic_resources_hg38"
 pheno_excel: "/home/aschmidt/COVID_WGS/resources/.no_upload/post_df3_HGI_sample_QC_summary.xlsx"
 array_files: "/home/aschmidt/COVID_WGS/resources/.no_upload/NAPKON_array/NAPKON_16_samples_bed.fam"
 phenotypes:
  - A1
  - B1
 masks: 
  - M0
  - M1
  - M3
  - M4
 af_cutoffs:
  - 0.05
  - 0.001
 populations:
  - EUR
 contigs_wo_X:
  - 1
 contigs:
  - "1"
 long: "long"
 medium: "medium"
 tmp_folder: "tmp/"
 cluster: "yes"
 LD_LIBRARY_PATH: "/home/aschmidt/miniconda3/lib"
 master_nodes_excluded: "node01"
 worker_nodes_excluded: "node01"
 PATH: "$(echo \"$PATH\")"
 PYTHONPATH: "/home/aschmidt/miniconda3/lib/python3.9/site-packages"
 spark_master_path: "/home/aschmidt/spark-3.1.1-bin-hadoop3.2/sbin/start-master.sh"
 spark_worker_path: "/home/aschmidt/spark-3.1.1-bin-hadoop3.2/sbin/start-worker.sh"
