---
 input_vcf: "/media/axel/Dateien/Arbeit_Gen/COVID_WGS/data_30_june/covid_df3.vcf.gz"
 fasta: "../data_30_june/run_temp_new_2/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
 phenotypes:
  - A2
  - B2
  - C2
 location_1000G: "../data_30_june/run_temp_new_2/"
 populations:
  - EUR
 contigs_wo_X:
  - 18
  - 21
 tmp_folder: "tmp/"
 cluster: "no"
 PATH: "$(echo \"$PATH\" | sed -e \"s>\/gpfs01\/share\/conda\/condabin:\/gpfs01\/share\/conda\/bin:>>\")"
 PYTHONPATH: "/home/aschmidt/scratch/conda/lib/python3.9/site-packages"
 spark_master_path: "/ceph01/scratch/aschmidt/spark/spark-3.1.1-bin-hadoop3.2/sbin/start-master.sh"
 spark_worker_path: "/ceph01/scratch/aschmidt/spark/spark-3.1.1-bin-hadoop3.2/sbin/start-worker.sh"
 LD_LIBRARY_PATH: ""

