---
 input_vcf: "/ceph01/projects/covid_wgs/glnexus/output/covid.genome.bcf"
 fasta: "/media/axel/Seagate Backup Plus Drive/annotation_sources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna" #"/ceph01/projects/bioinformatics_resources/Genomes/Human/GATK/hg38/Homo_sapiens_assembly38.fasta"
 phenotypes:
  - A2
  - B2
  - C2
 location_1000G: "/media/axel/Dateien/Arbeit_Gen/COVID_WGS/data_30_june/run_temp_new_2/" #"/ceph01/homedirs/aschmidt/scratch/WGS_GWAS_pipeline/"
 populations:
  - EUR
 contigs_wo_X:
  - 18
 tmp_folder: "tmp/"
 cluster: "no"
 master_nodes_excluded: "b101eth0,b102eth0,b103eth0,b104eth0,b105eth0,b106eth0,b107eth0,b201eth0"
 worker_nodes_excluded: "b101eth0,b102eth0,b103eth0,b104eth0,b105eth0,b106eth0,b107eth0,b201eth0"
 PATH: "$(echo \"$PATH\" | sed -e \"s>\/gpfs01\/share\/conda\/condabin:\/gpfs01\/share\/conda\/bin:>>\")"
 PYTHONPATH: "/home/aschmidt/scratch/conda/lib/python3.9/site-packages"
 spark_master_path: "/ceph01/scratch/aschmidt/spark/spark-3.1.1-bin-hadoop3.2/sbin/start-master.sh"
 spark_worker_path: "/ceph01/scratch/aschmidt/spark/spark-3.1.1-bin-hadoop3.2/sbin/start-worker.sh"
 LD_LIBRARY_PATH: "/home/aschmidt/scratch/conda/lib"
 database_dir: "/media/axel/Seagate Backup Plus Drive/annotation_sources/"
 pheno_excel: "/media/axel/Dateien/Arbeit_Gen/COVID_WGS/Sample_listen_erstellen/post_df3_HGI_sample_QC_summary.xlsx"
 array_files: "/media/axel/Seagate Backup Plus Drive/bosco_longCOVID/merged_original_data/merged_data.fam"
 long: "long"
 medium: "medium"
 annotations_dir: "/home/aschmidt/Arbeit_Gen/COVID_WGS/COVID_annotation/results/for_RVAS/"
